/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("se.handlar.toggle.java-library-conventions")
    id("io.spring.dependency-management")
}

dependencies {
    api(project(":list"))
}
